document.write('\
<div class="well">\
	<h3>2002 Honors Theses</h3>				\
	<div class="q">	\
		<h3 class="qhead"><a href="#q200201">An Evaluation of Tracking Methods for Human-Computer Interaction</a></h3>\
		<div class="answer" id="q200201">\
			<p><b>Author:</b> Christopher R. Fagiani</p>\
			<p><b>Title:</b> <a href="pdf/02ChristopherFagiani.pdf"><em> An Evaluation of Tracking Methods for Human-Computer Interaction</em></a></p>\
			<p><b>Advisor:</b> James Gips</p>\
			<p><b>Abstract</b></p>\
			<p><font size="4">The child human-computer interaction paradigm, based around the keyboard and mouse, has seen little change since the advent of modern computing. Since many desktop and laptop computers now come with cameras as standard equipment, it is desirable to employ them for next-generation human-computer interaction devices.</font></p>\
		</div>   <!-- end answer -->\
	</div><!-- end question -->	\
	<div class="q">	\
		<h3 class="qhead"><a href="#q200202">Real-Time Terrain Rendering and Scene Graph Management</a></h3>\
		<div class="answer" id="q200202">\
			<p><b>Author:</b> Cristopher Stauffer</p>\
			<p><b>Title:</b> <a href="pdf/02CristopherStauffer.pdf"><em> Real-Time Terrain Rendering and Scene Graph Management</em></a></p>\
			<p><b>Advisor:</b> Williams Ames</p>\
			<p><b>Abstract</b></p>\
			<p><font size="4">The development of computer-aided terrain rendering has over the years been the necessity of an array of applications such as topographical mapping, surgical and medical aids, as well as simulations and entertainment. The goal of rendering has been redefined over the past decade due to the introduction of systems capable of real-time terrain representation.</font></p>\
			<p><font size="4">Click <a href="attachments/02StaufferThesisCode.zip">HERE</a> to download Cristopher Stauffer\'s code.</font></p>	\
		</div>   <!-- end answer -->\
	</div><!-- end question -->	\
	<div class="q">	\
		<h3 class="qhead"><a href="#q200203">Middleman - Linking Data Sources and Wireless Devices</a></h3>\
		<div class="answer" id="q200203">\
			<p><b>Author:</b> Michael Tierney</p>\
			<p><b>Title:</b> <a href="pdf/02MichaelTierney.pdf"><em> Middleman - Linking Data Sources and Wireless Devices</em></a></p>\
			<p><b>Advisor:</b> Edward Sciore</p>\
			<p><b>Abstract</b></p>\
			<p><font size="4">The combined technological developments of Java and XML have helped to create many advances in portability and customizable presentation of data. My research, the development of the Middleman Server System, focused on combining the portable aspects of XML and Java with the seemingly natural pairing of XML and database connectivity.</font></p>\
		</div>   <!-- end answer -->\
	</div><!-- end question -->	\
	<div class="q">	\
		<h3 class="qhead"><a href="#q200204">Distributed Ray Tracing</a></h3>\
		<div class="answer" id="q200204">\
			<p><b>Author:</b> John Weicher</p>\
			<p><b>Title:</b> <a href="pdf/02JohnWeicher.pdf"><em> Distributed Ray Tracing</em></a></p>\
			<p><b>Advisor:</b> William Ames</p>\
			<p><b>Abstract</b></p>\
			<p><font size="4">Photo-realistic images are those that have been generated by a computer by doing mathematical and geometric calculations based on the physics of the real world, but are images which are indistinguishable from two-dimensional photographs taken of a real life three-dimensional scene. As computers became more powerful, several techniques were developed in attempts to do this. Raytracing is one of those techniques, and is probably one of the most popular 3d image-synthesis techniques in use today. Raytracing is actually a remarkably simple process, providing one has a bit of background understanding first.</font></p>\
			<p><font size="4">Click <a href="attachments/02WeicherThesisCode.zip">HERE</a> to download John Weicher\'s code.</font></p>	\
		</div>   <!-- end answer -->\
	</div><!-- end question -->	\
	<div class="q">	\
		<h3 class="qhead"><a href="#q200205">Error Tolerant Clustering of Gene Microarray Data</a></h3>\
		<div class="answer" id="q200205">\
			<p><b>Author:</b> Jay Cahill</p>\
			<p><b>Title:</b> <a href="pdf/02JayCahill.pdf"><em> Error Tolerant Clustering of Gene Microarray Data</em></a></p>\
			<p><b>Advisor:</b> Peter Clote</p>\
			<p><b>Abstract</b></p>\
			<p><font size="4">Gene microarray technology allows for unprecedented and massive production of biological data across multiple experimental conditions and in time series. Computer analysis of this data can help guide biological bench work toward the assignment of gene function, classification of cells and tissues and the ultimately assist in the diagnosis and treatment of disease. One approach to the analysis of microarray data is the identification of group of genes with common expression patterns or "clusters." The author implements an error-tolerant clustering algorithm due to Amir Ben-Dor, Ron Shamir and Zohar Yakhini. In their original paper, they defined a stochastic error model for microarray data, and, based on that model, prove that their algorithm recovers the underlying cluster structure of microarray data with high probability. In this paper, their results are replicated on artificial data. In addition, the author tests the stability of clusterings generated by the algorithm and compares the performance of discretized and non-discretized versions.</font></p>\
		</div>   <!-- end answer -->\
	</div><!-- end question -->	\
	<div class="q">	\
		<h3 class="qhead"><a href="#q200206">2-Dimensional Shape Categorization Using Polar Coordinate Representations</a></h3>\
		<div class="answer" id="q200206">\
			<p><b>Author:</b> Daniel Russo</p>\
			<p><b>Title:</b> <a href="pdf/02DanielRusso.pdf"><em> 2-Dimensional Shape Categorization Using Polar Coordinate Representations</em></a></p>\
			<p><b>Advisor:</b> Peter Kugel</p>\
			<p><b>Abstract</b></p>\
			<p><font size="4">This paper describes a method for comparing and categorizing shapes in BMP image files that involves storing the points of shapes as polar coordinates. In doing this, the calculations involved in the comparisons become simpler, and the overall running time of the comparison algorithm is significantly reduced.</font></p>\
		</div>   <!-- end answer -->\
	</div><!-- end question -->	\
</div>\
');